import { Strain, Submission, VaccineContent } from "@/types";

export const INITIAL_STRAINS: Strain[] = [
  {
    id: "str-001",
    name: "Synthetic Ministry Emergency Grid Shutdown Alert",
    technique: "doctored_screenshot",
    intent: "Induce civic panic and ATM cash bank runs before weekend elections",
    summary: "Fabricated official gazette screenshot claiming countrywide 72-hour power and bank server blackout starting midnight.",
    report_count: 3,
    regions_affected: ["Capital Area", "North District"],
    distributed_regions: ["Capital Area", "North District"],
    has_vaccine: true,
    created_at: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    vaccine: {
      id: "vac-001",
      strain_id: "str-001",
      title: "Fact Check: No Scheduled Grid Outage or Banking Freeze",
      explainer: "Official energy and central banking regulators confirm all power systems and ATM networks are operating normally. The circulating document uses a distorted department seal and non-existent circular number #2026-B89.",
      created_at: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    },
  },
  {
    id: "str-002",
    name: "Cloned Mayor Voice Note on Tap Water Contamination",
    technique: "cloned_voice",
    intent: "Promote private water filtration scam and sow municipal distrust",
    summary: "AI-cloned audio message impersonating the municipal commissioner warning citizens that municipal tap water is toxic with heavy metals.",
    report_count: 2,
    regions_affected: ["Coastal Region", "Rural Belt"],
    distributed_regions: ["Coastal Region"],
    has_vaccine: true,
    created_at: new Date(Date.now() - 30 * 3600 * 1000).toISOString(),
    vaccine: {
      id: "vac-002",
      strain_id: "str-002",
      title: "Audio Forensics: Synthetic Voice Clip Impersonating City Official",
      explainer: "Acoustic spectrum analysis detected speech synthesis artifacts (absence of natural room reverberation and irregular pitch inflection). The city water board has published daily laboratory safety certificates with zero toxicity.",
      created_at: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    },
  },
  {
    id: "str-003",
    name: "Fabricated WHO 87% Youth Memory Loss Clinical Study",
    technique: "fabricated_statistic",
    intent: "Sell dubious herbal memory booster supplements",
    summary: "Viral graphic citing a non-existent WHO 2026 report claiming 87% of students develop irreversible cognitive decline from standard syllabus study hours.",
    report_count: 2,
    regions_affected: ["South District", "North District", "Rural Belt"],
    distributed_regions: [],
    has_vaccine: false,
    created_at: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
  },
  {
    id: "str-004",
    name: "Recycled 2018 Cyclone Footage Framed as Impending Coastal Tsunami",
    technique: "out_of_context_image",
    intent: "Sensationalist clickbait and fishing port disruption",
    summary: "Viral TikTok/Reels clip using 2018 Pacific typhoon footage claiming a Category 5 superstorm will strike the local harbor in 4 hours.",
    report_count: 1,
    regions_affected: ["Coastal Region"],
    distributed_regions: [],
    has_vaccine: false,
    created_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_SUBMISSIONS: Submission[] = [
  // Linked to str-001 (Screenshot strain)
  {
    id: "sub-001",
    content_text: "Forwarded WhatsApp image showing official notice from Ministry of Power: 'Complete 3-day power blackout and internet suspension starting Friday 10 PM across Capital Area.'",
    image_url: "https://images.unsplash.com/photo-1588681664899-f142ff2dc9b1?auto=format&fit=crop&w=600&q=80",
    region: "Capital Area",
    language: "English",
    ai_suggested_technique: "doctored_screenshot",
    ai_confidence: 0.94,
    ai_summary: "Doctored administrative circular claiming an impending 72-hour total power & internet shutdown.",
    status: "confirmed",
    strain_id: "str-001",
    created_at: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
  },
  {
    id: "sub-002",
    content_text: "Everyone in North District is sharing this notification image about bank ATMs shutting down with power grid blackouts tonight. Is this true?",
    image_url: "",
    region: "North District",
    language: "English",
    ai_suggested_technique: "doctored_screenshot",
    ai_confidence: 0.91,
    ai_summary: "Duplicate report of emergency blackout notification causing ATM cash panic.",
    status: "confirmed",
    strain_id: "str-001",
    created_at: new Date(Date.now() - 44 * 3600 * 1000).toISOString(),
  },
  {
    id: "sub-003",
    content_text: "राजधानी क्षेत्र में बिजली और एटीएम बंद होने का सरकारी आदेश व्हाट्सएप पर घूम रहा है। क्या यह सही है?",
    image_url: "",
    region: "Capital Area",
    language: "Hindi (हिंदी)",
    ai_suggested_technique: "doctored_screenshot",
    ai_confidence: 0.89,
    ai_summary: "Hindi language variant of the synthetic government blackout decree.",
    status: "confirmed",
    strain_id: "str-001",
    created_at: new Date(Date.now() - 40 * 3600 * 1000).toISOString(),
  },

  // Linked to str-002 (Voice clone strain)
  {
    id: "sub-004",
    content_text: "Audio file received in coastal colony group. Voice sounds exactly like City Mayor telling residents 'Do not drink tap water, pipeline contaminated with chemical leak, buy bottled mineral water immediately.'",
    image_url: "",
    region: "Coastal Region",
    language: "English",
    ai_suggested_technique: "cloned_voice",
    ai_confidence: 0.96,
    ai_summary: "Synthetic cloned voice message of municipal leader alleging municipal water poisoning.",
    status: "confirmed",
    strain_id: "str-002",
    created_at: new Date(Date.now() - 30 * 3600 * 1000).toISOString(),
  },
  {
    id: "sub-005",
    content_text: "Un mensaje de voz del alcalde diciendo que el agua de grifo contiene toxinas letales y debemos comprar filtros de marca X.",
    image_url: "",
    region: "Rural Belt",
    language: "Spanish (Español)",
    ai_suggested_technique: "cloned_voice",
    ai_confidence: 0.92,
    ai_summary: "Spanish audio forward claiming tap water contamination to sell water filters.",
    status: "confirmed",
    strain_id: "str-002",
    created_at: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
  },

  // Linked to str-003 (Fabricated statistic)
  {
    id: "sub-006",
    content_text: "Infographic claiming 'WHO Bulletin #84: 87% of school teenagers suffer severe brain cell decay due to exams unless given SmartHerb elixir.'",
    image_url: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=600&q=80",
    region: "South District",
    language: "English",
    ai_suggested_technique: "fabricated_statistic",
    ai_confidence: 0.88,
    ai_summary: "Fabricated global health agency metric used to market unregulated dietary supplements.",
    status: "confirmed",
    strain_id: "str-003",
    created_at: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
  },
  {
    id: "sub-007",
    content_text: "Widespread post in student groups: 'WHO report confirms 87% memory degradation in North District exam candidates'.",
    image_url: "",
    region: "North District",
    language: "English",
    ai_suggested_technique: "fabricated_statistic",
    ai_confidence: 0.93,
    ai_summary: "Statistical disinformation regarding youth memory loss attributed falsely to WHO.",
    status: "confirmed",
    strain_id: "str-003",
    created_at: new Date(Date.now() - 16 * 3600 * 1000).toISOString(),
  },

  // Linked to str-004 (Out of context media)
  {
    id: "sub-008",
    content_text: "Instagram reel showing massive ocean waves destroying a pier with caption 'Massive Tsunami approaching Coastal Harbor right now, evacuate immediately!'",
    image_url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80",
    region: "Coastal Region",
    language: "English",
    ai_suggested_technique: "out_of_context_image",
    ai_confidence: 0.87,
    ai_summary: "Historical archived typhoon clip miscaptioned as an impending tsunami emergency.",
    status: "confirmed",
    strain_id: "str-004",
    created_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },

  // PENDING REVIEW SUBMISSIONS FOR SPOTTER / ANALYST PIPELINE DEMO
  {
    id: "sub-009",
    content_text: "Deepfake video of the National Health Minister announcing that all school vaccinations are canceled indefinitely because 'the virus has vanished overnight'. Looks like mouth movements are slightly desynced.",
    image_url: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=600&q=80",
    region: "Capital Area",
    language: "English",
    ai_suggested_technique: "deepfake",
    ai_confidence: 0.95,
    ai_summary: "AI-generated synthetic video of health official falsely declaring pandemic eradication.",
    status: "pending_review",
    strain_id: null,
    created_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
  {
    id: "sub-010",
    content_text: "ग्रामीण क्षेत्र में एक वायरल पर्चा: 'नया 5G टावर फसलों को 40% सूखा कर रहा है'। किसानों को टावर बंद करने की अपील।",
    image_url: "",
    region: "Rural Belt",
    language: "Hindi (हिंदी)",
    ai_suggested_technique: "fabricated_statistic",
    ai_confidence: 0.85,
    ai_summary: "Unsubstantiated pseudoscience flyer claiming telecom infrastructure damages agriculture.",
    status: "pending_review",
    strain_id: null,
    created_at: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
  },
  {
    id: "sub-011",
    content_text: "Screenshots of fake WhatsApp chat between university chancellor and students leaking supposed question papers for $50 crypto transfer.",
    image_url: "",
    region: "South District",
    language: "English",
    ai_suggested_technique: "doctored_screenshot",
    ai_confidence: 0.91,
    ai_summary: "Fabricated messenger conversation engineered to perpetrate academic examination fraud.",
    status: "pending_review",
    strain_id: null,
    created_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
  },
];
